apiVersion: v1
kind: Service
metadata:
  name: wings-infer-service
  labels:
    app: wings-infer
spec:
  type: LoadBalancer  # 可选: ClusterIP, NodePort, LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: wings-infer